// This file is auto-generated by @buzola/vite-plugin. Do not edit.
/* eslint-disable */

import { lazy, type ComponentType } from 'react';
import { buildRouteTree } from '@buzola/router';
import type { RouteConfig } from '@buzola/router';

import Route0 from './routes/_layout';
const Route1 = () => import('./routes/index').then(m => ({ default: m.default.component })) as Promise<{ default: ComponentType }>;
const Route2 = () => import('./routes/projects/detail').then(m => ({ default: m.default.component })) as Promise<{ default: ComponentType }>;
const Route3 = () => import('./routes/projects/run').then(m => ({ default: m.default.component })) as Promise<{ default: ComponentType }>;
const Route4 = () => import('./routes/settings').then(m => ({ default: m.default.component })) as Promise<{ default: ComponentType }>;

// Module augmentation for type-safe page-centric routing
declare module '@buzola/router' {
  interface BuzolaPageMap {
    'index': {};
    'projects/detail': { slug: string };
    'projects/run': { slug: string; runId: string };
    'settings': {};
  }
}

// Page registry — page ID → route pattern
export const pageRegistry: Record<string, string> = {
  'index': '/',
  'projects/detail': '/p/:slug',
  'projects/run': '/p/:slug/r/:runId',
  'settings': '/settings',
};

const routeConfigs: RouteConfig[] = [
  {
    path: '/',
    component: Route0,
    isLayout: true,
    children: [
      {
        path: '/',
        component: lazy(Route1),
        preload: Route1,
        isIndex: true,
      },
      {
        path: '/projects/detail',
        matchPath: '/p/:slug',
        component: lazy(Route2),
        preload: Route2,
      },
      {
        path: '/projects/run',
        matchPath: '/p/:slug/r/:runId',
        component: lazy(Route3),
        preload: Route3,
      },
      {
        path: '/settings',
        component: lazy(Route4),
        preload: Route4,
      },
    ],
  },
];

export const routes = buildRouteTree(routeConfigs);
